### ISSUE TITLE
zend-expressive 1.1 release

### ISSUE THREAD

**Issue by dzoeteman** [Naktibalda/codeception-zend-expressive-tests#4]
The codeception tests are currently failing because this package is no longer compatible with the just released version of zend-expressive, version 1.1. 

Error:
[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Type error: Argument 2 passed to Zend\Expressive\Container\ApplicationFacto  
  ry::injectRoutesAndPipeline() must be of the type array, object given, call  
  ed in /home/travis/build/Codeception/Codeception/frameworks-zend-expressive  
  /vendor/zendframework/zend-expressive/src/Container/ApplicationFactory.php   
  on line 179         

The injectRoutesAndPipeline() function expects an array for the config, but the config/config.php creates an ArrayObject.

**Comment by Naktibalda** [comment]
Fixed in 1.1.1
